### ISSUE TITLE
Inconsistent ETH wallet implementations

### ISSUE THREAD

**Issue by RmbRT** [hyperledger-labs/go-perun#9] opened 2021-03-03 10:15 UTC
Our `backend/ethereum/wallet/hd` uses `SignText(Hash(data))`, while `backend/ethereum/wallet/keystore` uses `SignHash(PrefixedHash(data))`, which is equivalent to `SignText(data)`. Please unify this.
Also, our wallets add 27 to the `v` byte of the signature when signing, when the Ethereum standard says that signatures should have a `v` in [0,1].

**Comment by ggwpez** [comment] 2021-03-03 10:21
We normally use `OpenZeppelin` to sign and verify signatures.  
They explicitly require `v` to be 27/28 as you can see [here](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/24a0bc23cfe3fbc76f8f2510b78af1e948ae6651/contracts/utils/cryptography/ECDSA.sol#L64).  
  
They justify this with:
```pre
EIP-2 still allows signature malleability for ecrecover(). Remove this possibility and make the signature
unique. Appendix F in the Ethereum Yellow paper (https://ethereum.github.io/yellowpaper/paper.pdf), defines
the valid range for s in (281): 0 < s < secp256k1n ÷ 2 + 1, and for v in (282): v ∈ {27, 28}. Most
signatures from current libraries generate a unique signature with an s-value in the lower half order.
```
as you can see in the link above. @RmbRT

**Comment by RmbRT** [comment] 2021-03-03 10:24
Yes, it's just causing problems when we use those wallets elsewhere as a drop-in replacement for an Ethereum-compliant wallet that returns v in [0,1]. Also, we should at least unify the behaviour (hash vs not hash message again), so that at least the wallets are consistent within the project. @ggwpez

**Comment by ggwpez** [comment] 2021-03-03 10:30
I like the unification with the different hash functions.

Would the change for `v` from 27/28 to 0/1 necessitate many changes in *go-perun*? I think we should estimate that before deciding.

**Comment by RmbRT** [comment] 2021-03-03 10:54
Regarding the hashing, I think it is best to remove the double hashing for better compatibility with code that does not expect double hashing.

**Comment by manoranjith** [comment] 2021-03-03 11:21
I think, both the implementations (`hd` and `keystore`) currently do double hashing. The first hash the data of arbitrary length, then prefix the phrase `\x19Ethereum Signed Message:\n32` to the hash and again hash the resulting byte array.

In this way them seem to be consistent with each other. See the implementation of [`PrefixedHash`](https://github.com/hyperledger-labs/go-perun/blob/37f6187c1df8d05409853c4eb7301a384f12923b/backend/ethereum/wallet/backend.go#L82) used in keystore implementation. See the first hashing step ([here](https://github.com/hyperledger-labs/go-perun/blob/37f6187c1df8d05409853c4eb7301a384f12923b/backend/ethereum/wallet/hd/account.go#L39)), the implementation of [`SignText`](https://github.com/miguelmota/go-ethereum-hdwallet/blob/a60dcd172b4c8615143458ab105b396a87ab9d14/hdwallet.go#L418) in the `hdwallet` library that we use and the [`accounts.TextHash`](https://github.com/ethereum/go-ethereum/blob/ba999105ef89473cfe39e5e53354f7099e67a290/accounts/accounts.go#L183) function used by that implementation.

Also, if these two implementations were to be inconsistent with each other, I would expect [this generic test](https://github.com/hyperledger-labs/go-perun/blob/37f6187c1df8d05409853c4eb7301a384f12923b/wallet/test/wallettest.go#L46) in [wallet/test/wallettest.go] to fail.

**Comment by manoranjith** [comment] 2021-03-03 11:27
Hence, if we need to remove double hashing (for any reason), I think we need to update both the implementations (`hd` and `keystore`) such that hashing is done only once.

**Comment by RmbRT** [comment] 2021-03-03 11:33
You're right, it seems that we always do double hashing, however, this is still not standard wallet behaviour as far as I know. This already caused problems when using migumolta's hdwallet and perun wallets in one project.

**Comment by manoranjith** [comment] 2021-03-03 11:37
Okay, i have no comments regarding removal / retaining of the double hashing step. I just wanted to point out that both the implementations do double hashing.

**Comment by matthiasgeihs** [comment] 2021-03-09 14:09
It seems like the point of the issue is not valid anymore. Closing it for now.

**Closed by matthiasgeihs** 2021-03-09 14:09 UTC
Labels: bug
